apiVersion: v1
kind: Service
metadata:
  name: landmark-app-lb
  namespace: landmark
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
    service.beta.kubernetes.io/aws-load-balancer-subnets: "subnet-0bce3c6863303e601,subnet-000a4d4a54c226a5f"
spec:
  type: LoadBalancer
  selector:
    app: landmark-app
  ports:
    - port: 80
      targetPort: 5000
      protocol: TCP
